### ISSUE TITLE
Markdown (Text) elements restrict movement to edge

### ISSUE THREAD

**Issue by carlos-kelly** [FormidableLabs/spectacle-visual-editor#208]
- Restrict dragging of markdown elements to a 16px edge around the element
- Allow for a single click after selection to change into edit mode
- It is not expected to be able to drag and resize when in edit mode

**Comment by fritz-c** [comment]
@carlos-kelly Sorry, just getting back to this now. Based on your description, I would assume you're aiming for an editing experience similar to Keynote. If that is the case, there is one compromise we don't have to make: dragging being restricted to the outer edge of text boxes. That is a compromise Google Slides and PowerPoint make in order to be able to initiate editing with a single click regardless of previous context.
